# -*- coding: utf-8 -*-
"""PF_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnRQ0FzRS5_EzK1waOgGweRokKrFmzfg
"""

##CHAPTER 11
##Q1
Total_products=eval(input("Enter the number of products: "))
dict1={}
for i in range(Total_products):
  name=input("Enter the name of the product: ")
  price=eval(input("Enter the price of the product: "))
  dict1[name]=price             

while True:
  namecheck=input("Enter the product name for the price: ")
  if namecheck in dict1:
    print("The price of ",namecheck," is",dict1[name])
  else:
    print("The entered product is not in the entered dictionary. ")

print(dict1)

##Q2
Total_products=eval(input("Enter the number of products: "))
dict1={}
for i in range(Total_products):
  name=input("Enter the name of the product: ")
  price=eval(input("Enter the price of the product: "))
  dict1[name]=price             

for i in range(Total_products):
  namecheck=input("Enter the product name for the price: ")
  if namecheck in dict1:
    print("The price of ",namecheck," is",dict1[name])
  else:
    print("The entered product is not in the entered dictionary. ")

print(dict1)

amount1 = eval(input("Enter a dollar amount: "))
for key ,values in dict1.items():
    if  int(values) < amount1:
        print (key ,"->",values)

##Q3(a),(e)
months = {"jan":31, "feb":28, "march":31, "april":30, "may":31, "june":30, "july":31, "aug":31, "sept":30, "oct":31, "nov":30, "dec":31}

month_input = input("Enter the name of the month: ")
print("Number of days in ",month_input,"=",months[month_input])

##Q3(b)
months = {"jan":31, "feb":28, "march":31, "april":30, "may":31, "june":30, "july":31, "aug":31, "sept":30, "oct":31, "nov":30, "dec":31}
sorted_keys = list(months.keys())
sorted_keys.sort()
print(sorted_keys)

##Q3(c)
months = {"jan":31, "feb":28, "march":31, "april":30, "may":31, "june":30, "july":31, "aug":31, "sept":30, "oct":31, "nov":30, "dec":31}
print("The following months have a total of 31 days: ")
for i in months:
    if months[i]==31:
        print(i)

##Q3(d)
months = {"jan":31, "feb":28, "march":31, "april":30, "may":31, "june":30, "july":31, "aug":31, "sept":30, "oct":31, "nov":30, "dec":31}
print("Months sorted by number of days: ")
print("feb")
for i in months:
    if months[i]==30:
        print(i)
for i in months:
    if months[i]==31:
        print(i)

##Q4
d1={"A":1234,"B":5678,"C":9101,"D":7364,"E":8563,"F":5913,"G":4684,"H":3485,"I":6341,"J":9452}
username=input("Enter your username : ")
if username not in d1.keys():
    print("you are not a valid user of the system.")
else:
    password=eval(input("Enter your password :"))
    if password in d1.values() and username in d1.keys():
        print("You have sucessfully logged in")
    else:
        print("you entered wrong password ")

##Q5(a)
no_of_teams = eval(input("Enter the number of teams: "))
team_scores = {}
for i in range(no_of_teams):
  team_name = input("Enter the team's name: ")
  wins = int(input("Enter number of wins: "))
  losses = int(input("Enter number of losses: "))
  team_scores[team_name] = [wins, losses]

team_find = input("Enter the name of the team to find percentage: ")
print("Team ", team_find, "'s winning percentage = ", (team_scores[team_find][0]/sum(team_scores[team_find]))*100)

#Q5(b)
winning_team = [i[0] for i in team_scores.values()]
print(winning_team)

#Q5(c)
winning_record = []
for i in team_scores:
  if team_scores[i][0]>0:
    winning_record.append(i)
print(winning_record)

##Q6
num_of_teams =int(input("Enter Number Of Teams: "))
total_teams_dict={}
for team in range(num_of_teams):
    team_name = input("Enter Team name: ")
    team_scores =[]
    wins = int(input("Enter Win: "))
    losses = int(input("Enter Losses: "))
    team_scores.extend((wins,losses))
    total_teams_dict.update({team_name:team_scores})

print(total_teams_dict)

##Q7
list1=[1,2,3,4,5
    ,6,7,8,9,0
    ,2,5,8,3,9
    ,9,5,3,2,7
    ,3,4,7,5,8]
dict1={}
for i in range(len(list1)):
  if i in list1:
    dict1[i]=list1.count(i)
print(dict1)

##Q8
import random
cards = {"One":1,"Two":2,"Three":3,"Four":4,"Five":5,"Six":6,"Seven":7,"Eight":8,"Nine":9,"Ten":10}
cards_each = 3
player1card =[]
player2card =[]
for card in range(cards_each):
    card1 = random.choice(list(cards.values()))
    card2 = random.choice(list(cards.values()))
    player1card.append(card1)
    player2card.append(card2)
print(player1card,player2card)

if sum(player1card)>sum(player2card):
    print("Player 1 wins with ",sum(player1card)," against Player 2 with",sum(player2card))
elif sum(player2card)>sum(player1card):
    print("Player 2 wins with ",sum(player2card)," against Player 1 with",sum(player1card))

##Q14
l=[{'name':'Birdy', 'phone':'000-1685', 'email':'Birdy@mail.net'},
{'name':'Birdy2', 'phone':'000-8965', 'email':'Birdy2mail.net'},
{'name':'Birdy3', 'phone':'000-9865', 'email':'Birdy3mail.net'},
{'name':'Birdy4', 'phone':'000-4986', 'email':''}]
for i in l:
  if i["email"]=='':
    print(i["name"])

##Q15